apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbkm-fe
spec:
  revisionHistoryLimit: 3
  replicas: 1
  template:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: http://vault.vault.svc.cluster.local:8200
        vault.security.banzaicloud.io/vault-agent: "false"
        vault.security.banzaicloud.io/vault-path: kubernetes
        vault.security.banzaicloud.io/vault-role: mbkm-dev
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      containers:
        - name: app
          env:
            - name: TZ
              value: vault:mbkm/data/dev/env#TZ
          resources:
            limits:
              cpu: 200m
              memory: 254M
            requests:
              cpu: 100m
              memory: 128M
